[workspace]
members = ["dev-log-macros", "dev-log"]
resolver = "2"

[workspace.package]
authors = ["Rifine 231310326@mail.dhu.edu.cn"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/Rifine/dev-log"
edition = "2021"