[package]
name = "dev-log"
version = "0.1.0"
edition = "2024"

[dependencies]
dev-log-macros = { path = "./dev-log-macros", version = "*"}

[features]
default = ["allow-print"]
allow-print = []
stack-trace = []
shadow-std = []